const TEXT = "#1F2937";
const BACKGROUND = "#F3F4F6";
const ON_BACKGROUND = "#E5E7EB";
const SURFACE = "#FFFFFF";
const ON_SURFACE = "#E5E7EB";
const BORDER = "#D1D5DB";
const PRIMARY = "#2563EB";
const ON_PRIMARY = "#FFFFFF";
const ERROR = "#991B1B";
const ON_ERROR = "#FFFFFF";
const SUCCESS = "#15803D";
const ON_SUCCESS = "#FFFFFF";
const WARNING = "#DC6803";
const ON_WARNING = "#FFFFFF";

//dark
const DARK_TEXT = "#F3F4F6";
const DARK_BACKGROUND = "#1F2937";
const DARK_ON_BACKGROUND = "#E5E7EB";
const DARK_SURFACE = "#1F2937";
const DARK_ON_SURFACE = "#E5E7EB";
const DARK_BORDER = "#4B5563";
const DARK_PRIMARY = "#2563EB";
const DARK_ON_PRIMARY = "#FFFFFF";
const DARK_ERROR = "#991B1B";
const DARK_ON_ERROR = "#FFFFFF";
const DARK_SUCCESS = "#15803D";
const DARK_ON_SUCCESS = "#FFFFFF";
const DARK_WARNING = "#DC6803";
const DARK_ON_WARNING = "#FFFFFF";

export {
    TEXT,
    BACKGROUND,
    ON_BACKGROUND,
    SURFACE,
    ON_SURFACE,
    BORDER,
    PRIMARY,
    ON_PRIMARY,
    ERROR,
    ON_ERROR,
    SUCCESS,
    ON_SUCCESS,
    WARNING,
    ON_WARNING,
    DARK_TEXT,
    DARK_BACKGROUND,
    DARK_ON_BACKGROUND,
    DARK_SURFACE,
    DARK_ON_SURFACE,
    DARK_BORDER,
    DARK_PRIMARY,
    DARK_ON_PRIMARY,
    DARK_ERROR,
    DARK_ON_ERROR,
    DARK_SUCCESS,
    DARK_ON_SUCCESS,
    DARK_WARNING,
    DARK_ON_WARNING
}